---
name: Lint CI

"on":
  push:
    branches:
      - master
    paths:
      - 'Makefile'
      - 'bin/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Makefile'
      - 'bin/**'

permissions:
  contents: read

jobs:
  lint:
    name: Shell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install socat mpv rofi
          python -m pip install yt-dlp
      - name: Setup some envs
        run: |
          echo "HOME=$HOME" >> "$GITHUB_ENV"
          echo "PATH=$PATH:$HOME/.local/bin" >> "$GITHUB_ENV"
      - name: Shellcheck scripts
        run: |
          shellcheck -s bash bin/mpvctl
          shellcheck -s bash bin/ytdl-mpv
      - name: Make install
        run: make install
      - name: Run mpvctl help
        run: mpvctl --help
      - name: Run ytdl-mpv help
        run: ytdl-mpv --help
