---
name: Releaser CD

"on":
  push:
    tags:
      - "v[0-9].[0-9].[0-9]+"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
      - name: Generate changelog latest
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5
        id: cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
      - name: Get tag
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF:10}" >> "$GITHUB_ENV"
      - name: Create release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b
        with:
          name: ytdl-mpv ${{ env.TAG }}
          body: ${{ steps.cliff.outputs.content }}
          generate_release_notes: true
  changelog:
    name: Changelog
    needs:
      - release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
      - name: Get tag
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF:10}" >> "$GITHUB_ENV"
      - name: Refresh changelog
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5
        with:
          config: cliff.toml
          args: --verbose --tag ${{ env.TAG }}
        env:
          OUTPUT: CHANGELOG.md
      - name: Commit changelog
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321
        with:
          message: "chore(CHANGELOG): add ytdl-mpv ${{ env.TAG }} changes"
          add: 'CHANGELOG.md'
          new_branch: master
